apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-deployment
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
      - name: nginx-hello
        image: {{ .Values.container.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          privileged: false
