apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  labels:
    app: {{ .Values.container.name }}
spec:
  ports:
    - name: hello-nginx-service
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.container.name }}
  type: {{ .Values.service.type }}
